### ISSUE TITLE
Compile and test the app

### ISSUE THREAD

**Issue by lsalamon** [fdiskyou/WinAllocTracer#1]
Hi, where I find module msvc_compat.h ?

**Comment by lsalamon** [comment]
Ok, I find then in PIN folder.

**Comment by lsalamon** [comment]
I try to compile using Visual Studio 2017 15.8.8 but no have success.
I download PIN version pin-3.7-97619-g0d0c92f4f-msvc-windows put includes directories in right places.
I need to inform sub folder include path ..\..\..\extras\xed-ia32\include\xed;
But in x86 compilation give me this error:
1>c:\sources\c\debug\extras\crt\include\windows.h(34): fatal error C1189: #error:  Must define _WINDOWS_H_PATH_
1>Done building project "WinMallocTracer.vcxproj" -- FAILED.

x64 has this:
1>c:\sources\c\debug\extras\crt\include\stddef.h(68): error C2371: 'size_t': redefinition; different basic types
1>c:\sources\c\debug\winmalloctracer\winmalloctracer\winmalloctracer\winmalloctracer.cpp: note: see declaration of 'size_t'
1>c:\sources\c\debug\extras\stlport\include\stl\_algobase.h(255): warning C4244: 'initializing': conversion from '__int64' to 'ptrdiff_t', possible loss of data
1>c:\sources\c\debug\extras\stlport\include\stl\_algobase.h(255): warning C4244: 'initializing': conversion from '__int64' to 'const ptrdiff_t', possible loss of data
1>c:\sources\c\debug\extras\stlport\include\stl\_algobase.h(625): warning C4244: 'initializing': conversion from '__int64' to 'ptrdiff_t', possible loss of data
1>c:\sources\c\debug\extras\stlport\include\stl\_algobase.h(625): warning C4244: 'initializing': conversion from '__int64' to 'const ptrdiff_t', possible loss of data
1>c:\sources\c\debug\extras\stlport\include\stl\_algobase.h(626): warning C4244: 'initializing': conversion from '__int64' to 'ptrdiff_t', possible loss of data
1>c:\sources\c\debug\extras\stlport\include\stl\_algobase.h(626): warning C4244: 'initializing': conversion from '__int64' to 'const ptrdiff_t', possible loss of data
1>c:\sources\c\debug\extras\stlport\include\stl\char_traits.h(83): error C2118: negative subscript
1>c:\sources\c\debug\winmalloctracer\include\pin\level_base.plh(99): fatal error C1083: Cannot open include file: 'xed-iclass-enum.h': No such file or directory
1>Done building project "WinMallocTracer.vcxproj" -- FAILED.

Any help is welcome.

**Comment by fdiskyou** [comment]
The build for x64 needs some love, the x86 build should be fine.
Did you download the whole project?

**Comment by lsalamon** [comment]
Yes, I download all sources in zip format.
What is relative path do put pin files?

**Comment by fdiskyou** [comment]
No, Pin should be installed under c:\pin. Check this post for more information: http://deniable.org/reversing/binary-instrumentation

**Comment by lsalamon** [comment]
What path you put your project WinMallocTracer to work with relative path's ?
Additional Include Directories:
..\..\include\pin;..\..\include\pin\gen;..\InstLib;..\..\..\extras\xed-ia32\include;..\..\..\extras\components\include;..\..\..\extras\stlport\include;..\..\..\extras;..\..\..\extras\libstdc++\include;..\..\..\extras\crt\include;..\..\..\extras\crt;..\..\..\extras\crt\include\arch-x86;..\..\..\extras\crt\include\kernel\uapi;..\..\..\extras\crt\include\kernel\uapi\asm-x86;%(AdditionalIncludeDirectories)

**Comment by fdiskyou** [comment]
No, check the post. It's c:\pin\source\tools\

**Comment by fdiskyou** [comment]
Closing.

**Comment by David1119** [comment]
> No, check the post. It's c:\pin\source\tools\

not work on Visual studio 2017&2019
![image](https://user-images.githubusercontent.com/7445954/70515863-03f71400-1b71-11ea-9df8-a06f078d5ec1.png)

**Comment by fdiskyou** [comment]
Read the blog post please.

**Comment by fdiskyou** [comment]
@David1119 @lsalamon sorry it's a bit late but after trying to build this with latest Pin and Visual Studio 2019 and hit the same issues as you. Since I use `Windows.h` in my Pintool there's an extra define that's missing and I actually didn't document (as I thought I did). Check: https://software.intel.com/sites/default/files/managed/8e/f5/PinCRT.pdf

Basically you need  to add this to the compilation flags:

```
/D_WINDOWS_H_PATH_="$(ORIGINAL_WINDOWS_H_PATH)"
```

I'll commit a full VS2019 project shortly and document the issue.
